using System.Collections;
using UnityEngine;

/// <summary>
/// Reusable audio and simple visual feedback for any interactable object.
/// Attach alongside an <see cref="IInteractable"/> implementation on the same GameObject.
/// <para>
/// The interactable script calls <see cref="PlaySuccess"/> or <see cref="PlayFailure"/>
/// explicitly — this component does NOT hook into <see cref="IInteractable"/> automatically,
/// keeping the interaction contract clean and composable.
/// </para>
/// </summary>
[DisallowMultipleComponent]
[RequireComponent(typeof(AudioSource))]
public sealed class InteractionFeedback : MonoBehaviour
{
    [Header("Audio")]
    [Tooltip("Played on a successful interaction.")]
    [SerializeField] private AudioClip successSound;

    [Tooltip("Played on a failed interaction.")]
    [SerializeField] private AudioClip failureSound;

    [Header("Visual (optional)")]
    [Tooltip("A small indicator mesh (e.g. LED). Leave empty if the object has no visual indicator.")]
    [SerializeField] private Renderer indicatorRenderer;

    [SerializeField] private Color successColor = Color.green;
    [SerializeField] private Color failureColor = Color.red;
    [SerializeField] private Color idleColor = Color.gray;

    [Tooltip("Seconds before the indicator returns to idle color after feedback.")]
    [SerializeField, Min(0.1f)] private float colorResetDelay = 2f;

    private AudioSource audioSource;
    private MaterialPropertyBlock propertyBlock;
    private Coroutine resetCoroutine;

    private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
    private static readonly int EmissionColorId = Shader.PropertyToID("_EmissionColor");

    // ── Public API ─────────────────────────────────────────────────────

    /// <summary>
    /// Plays the success sound and flashes the indicator green.
    /// </summary>
    public void PlaySuccess()
    {
        Debug.Log($"[InteractionFeedback] PlaySuccess() called on '{gameObject.name}'. " +
                  $"successSound={(successSound != null ? successSound.name : "NULL")}", this);
        PlayClip(successSound);
        FlashIndicator(successColor);
    }

    /// <summary>
    /// Plays the failure sound and flashes the indicator red.
    /// </summary>
    public void PlayFailure()
    {
        Debug.Log($"[InteractionFeedback] PlayFailure() called on '{gameObject.name}'. " +
                  $"failureSound={(failureSound != null ? failureSound.name : "NULL")}", this);
        PlayClip(failureSound);
        FlashIndicator(failureColor);
    }

    // ── Lifecycle ──────────────────────────────────────────────────────

    private void Awake()
    {
        audioSource = GetComponent<AudioSource>();

        if (audioSource == null)
        {
            Debug.LogError("[InteractionFeedback] No AudioSource found — audio will not play.", this);
            return;
        }

        audioSource.playOnAwake = false;

        // NOTE: spatialBlend is NOT forced here. Leave it at the Inspector value
        // (default 0 = 2D) so audio is always audible. Designers can increase it
        // toward 1 (3D) in the Inspector after tuning minDistance / maxDistance /
        // rolloff to match their scene scale.

        // ── Audio environment diagnostics ──
        AudioListener listener = FindFirstObjectByType<AudioListener>();
        Debug.Log($"[InteractionFeedback] Awake on '{gameObject.name}' — " +
                  $"AudioSource={audioSource.enabled}, " +
                  $"volume={audioSource.volume}, " +
                  $"mute={audioSource.mute}, " +
                  $"spatialBlend={audioSource.spatialBlend}, " +
                  $"AudioListener={(listener != null ? listener.gameObject.name : "*** MISSING — NO AUDIO WILL PLAY ***")}", this);

        propertyBlock = new MaterialPropertyBlock();

        if (indicatorRenderer != null)
        {
            SetIndicatorColor(idleColor);
        }
    }

    // ── Internals ──────────────────────────────────────────────────────

    private void PlayClip(AudioClip clip)
    {
        if (clip == null)
        {
            Debug.LogWarning("[InteractionFeedback] AudioClip is null — skipping playback.", this);
            return;
        }

        if (audioSource == null)
        {
            Debug.LogError("[InteractionFeedback] AudioSource is null — cannot play clip.", this);
            return;
        }

        AudioListener listener = FindFirstObjectByType<AudioListener>();
        if (listener == null)
        {
            Debug.LogError("[InteractionFeedback] AudioListener is NULL! Sound will be generated by AudioSource but cannot be heard by the player.", this);

            // Minimal runtime fallback: attach AudioListener to the active camera so audio plays immediately.
            Camera mainCam = Camera.main != null ? Camera.main : FindFirstObjectByType<Camera>();
            if (mainCam != null)
            {
                listener = mainCam.gameObject.AddComponent<AudioListener>();
                Debug.LogWarning($"[InteractionFeedback] Auto-recovery: Added AudioListener component to '{mainCam.name}'. Please add AudioListener to the Player prefab camera permanently.", mainCam);
            }
        }

        Debug.Log($"[InteractionFeedback] PlayClip PRE-FIRE — " +
                  $"clip='{clip.name}', " +
                  $"clipLength={clip.length:F2}s, " +
                  $"clipLoadState={clip.loadState}, " +
                  $"audioSource.exists={(audioSource != null)}, " +
                  $"audioSource.enabled={audioSource.enabled}, " +
                  $"audioSource.gameObject.activeInHierarchy={audioSource.gameObject.activeInHierarchy}, " +
                  $"audioSource.volume={audioSource.volume}, " +
                  $"audioSource.mute={audioSource.mute}, " +
                  $"audioSource.spatialBlend={audioSource.spatialBlend}, " +
                  $"audioSource.isPlaying={audioSource.isPlaying}, " +
                  $"AudioListener={(listener != null ? listener.gameObject.name : "MISSING")}, " +
                  $"AudioListener.volume={AudioListener.volume}, " +
                  $"AudioListener.pause={AudioListener.pause}", this);

        // PlayOneShot allows overlapping sounds without interrupting the current clip.
        audioSource.PlayOneShot(clip);

        Debug.Log($"[InteractionFeedback] PlayClip POST-FIRE — " +
                  $"audioSource.isPlaying={audioSource.isPlaying} (Note: PlayOneShot virtual voices do not alter isPlaying on null clip)", this);
    }

    private void FlashIndicator(Color color)
    {
        if (indicatorRenderer == null)
        {
            return;
        }

        // Cancel any pending reset so the latest feedback wins.
        if (resetCoroutine != null)
        {
            StopCoroutine(resetCoroutine);
        }

        SetIndicatorColor(color);
        resetCoroutine = StartCoroutine(ResetIndicatorAfterDelay());
    }

    private void SetIndicatorColor(Color color)
    {
        if (indicatorRenderer == null)
        {
            return;
        }

        indicatorRenderer.GetPropertyBlock(propertyBlock);
        propertyBlock.SetColor(BaseColorId, color);
        propertyBlock.SetColor(EmissionColorId, color);
        indicatorRenderer.SetPropertyBlock(propertyBlock);
    }

    private IEnumerator ResetIndicatorAfterDelay()
    {
        yield return new WaitForSeconds(colorResetDelay);
        SetIndicatorColor(idleColor);
        resetCoroutine = null;
    }
}
